import Head from "next/head";
import Image from "next/image";
import FooterBanner from "../components/footerbanner";
import HomeBanner from "../components/homeBanner";
import ServiceCard from "../components/ServiceCard";
import WhychooseUS from "../components/whychooseus";
import Workprocess from "../components/Workprocess";
import styles from "../styles/Home.module.css";
import services from "./json/services.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Xillixtech. Mobile and Desktop Development</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeBanner />
      <div className="mt-10">
        <WhychooseUS />
      </div>
     <section className="h-full">
     <div className="container">
        <div className="mt-20 ">
          <div className="heading-area mt-10 mb-10 text-center">
            <div className="sub-title">
              <span className="font-semibold">SERVICES</span>
            </div>
            <div className="title">
              <h3 className="text-3xl font-semibold">
                We Are Offering All Kinds of IT Solutions Services
              </h3>
            </div>
          </div>
        </div>
        <div className="max-[640px]:grid max-[640px]:grid-cols-1 max-[820px]:grid max-[820px]:grid-cols-2  lg:grid lg:grid-cols-3 gap-10 mt-20">
          {services.slice(0, 3).map((item, idx) => (
            <ServiceCard {...item}></ServiceCard>
          ))}
        </div>
        <div className="mt-10 mb-3 text-center mt-20">
          <a href="/services" className="xillix_btn">
            {" "}
            View All Services{" "}
          </a>
        </div>
      </div>
     </section>
      <div className="">
        <Workprocess />
      </div>
      <div className="">
        <FooterBanner />
      </div>
      {/* <main className={styles.main}>
     
      </main> */}
    </div>
  );
}
